[tasks.build]
command = "cargo"
args = ["build"]

[tasks.dev]
command = "cargo"
install_crate = "cargo-nextest"
dependencies = ["test"]
args = ["watch", "-x" , "run"]

[tasks.test]
command = "cargo"
args = ["nextest", "run"]
